### ISSUE TITLE
ehcache UpdateChecker error log

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keypass#136]
```
time=2020-06-16T08:08:57.106Z | lvl=DEBUG | corr= | trans=n/a | srv= | subsrv=n/a | comp=KEYPASS | op=UpdateChecker | msg=Update check failed: 
java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.terracotta.org/kit/reflector?pageID=update.properties&patch=UNKNOWN&tc-product=ehcache-core+2.8.9&tc-version=2.8.9&uptime-secs=1&kitID=ehcache.default&jvm-version=1.8.0_252&os-name=Linux&id=-1408172021&source=ehcache-core&jvm-name=OpenJDK+64-Bit+Server+VM&platform=amd64
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[na:1.8.0_252]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[na:1.8.0_252]
	at net.sf.ehcache.util.UpdateChecker.getUpdateProperties(UpdateChecker.java:153) [keypass.jar:1.5.0]
	at net.sf.ehcache.util.UpdateChecker.doCheck(UpdateChecker.java:117) [keypass.jar:1.5.0]
	at net.sf.ehcache.util.UpdateChecker.checkForUpdate(UpdateChecker.java:104) [keypass.jar:1.5.0]
	at net.sf.ehcache.util.UpdateChecker.run(UpdateChecker.java:95) [keypass.jar:1.5.0]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_252]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_252]
```

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-keypass/pull/135/
